spring.application.name=condoflow

# Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/condoflow_db
spring.datasource.username=root
spring.datasource.password=1234

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Porta da aplicação
server.port=8080