spring.application.name=condoflow

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/condoflow_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8090